version: '3.8'

services:
  php:
    build:
      context: ./docker
    container_name: aikido_php
    volumes:
      - ./aikido-asociacion:/var/www/html
      - ./docker/php-config.ini:/usr/local/etc/php/conf.d/custom.ini
    expose:
      - 9000
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: aikido_nginx
    ports:
      - "8080:80"
    volumes:
      - ./aikido-asociacion:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:5.7
    container_name: aikido_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aikido
      MYSQL_USER: aikido_user
      MYSQL_PASSWORD: aikido_pass
    volumes:
      - aikido_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  aikido_mysql_data: